# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://halotroop.com"

baseurl: /blog_2

# Google tracking id

google-tracking-id: ""

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Caroline Joy Bell"
title: "Caroline's Blog 2.0"
description: "Blog of a sandbox lover."
keywords: "blog, tech, minecraft, modder, modding, sandbox, mods, downloads"
favicon: "/img/avatar.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"
logo: "/img/author.png" # leave blank if you don't want a logo

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 999999999
lines: # You can add HTML Tags in the Text
  - text: "Splash text!"
  - text: "Penis!"
  - text: "Vagina!"
  - text: "Not for kids!"
  - text: "Boobs with the fur!"
  - text: "Furries welcome!"
  - text: "Bigots not welcome!"
  - text: "1% sugar!"
  - text: "150% hyperbole!"
  - text: "Cogito ergo sum!"
  - text: "Distribute!"
  - text: "Always dig down!"
  - text: "aoeu is a bad password!"
  - text: "Vote for net neutrality!"
  - text: "Let's start a riot!"
  - text: "All Cats Are Beautiful!"
  - text: "Check out the Far Lands!"
  - text: "90% buggy!"
  - text: "All inclusive*!"
  - text: "Euclidean!"
  - text: "Indie!"
  - text: "Fuck the police!"
  - text: "Play him off, Octocat!"
  - text: "Random splash!"
  - text: "Fully up-to-date!"
  - text: "Try Minecraft!"
  - text: "Try Better Than Wolves!"
  - text: "Try New Frontier Craft!"
  - text: "Uses LWJGL!"
  - text: "Make life take the lemons back!"
  - text: "Get mad!"
  - text: "I don't want your damn lemons!"
  - text: "Demand to see life's manager!"
  - text: "Do you know who I am?!"
  - text: "Caroline, Caroline, Caroline!"
  - text: "She is a gem."
  - text: "Now you're thinking with portals!"
  - text: "NP is not in P!"
  - text: "Wear your mask!"
  - text: "Get vaccinated!"
  - text: "Welcome!"
  - text: "Bienvenidos!"
  - text: "Enchanté!"
  - text: "Very concerning!"
  - text: "assert fabric > forge;"
  - text: "Viva la revolucion!"
  - text: "Try Viva Piñata!"
  - text: "Cat! I'm a kitty cat!"
  - text: "We're no strangers to love!"
  - text: "100% vegan!"

me-img: "https://github.com/halotroop2288.png?size=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "red"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 100

paginate: 10

email-share: True
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: False

disqus-shortname: "halotroop"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "https://fabricmc.net/assets/logo.png"
    date: "January 1st, 2020"
    description: "Started making Minecraft mods with Fabric"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "caroline@halotroop.com"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Caroline is a cat-girl with too much time on her hands. She loves virtual sandboxes, and programming."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/ha1otroop2288"
  - title: "github"
    url: "https://github.com/halotroop2288"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
